###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: blizzard-api-redis

    postgres:
      image: postgres:11.1-alpine
      container_name: blizzard-api-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=12345678
        - POSTGRES_DB=db_app
      ports:
        - "9004:5432"

    webserver:
      image: nginx:alpine
      container_name: blizzard-api-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: blizzard-api-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

